DROP TABLE PRODUCT;
DROP TABLE CATEGORY;

CREATE TABLE CATEGORY
(
    CATEGORY_ID INT PRIMARY KEY,
    CATEGORY_NAME VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCT
(
    PRODUCT_ID INT PRIMARY KEY,
    CATEGORY_ID INT NOT NULL,
    PRODUCT_NAME VARCHAR(50) NOT NULL,
    PRODUCT_PRICE FLOAT NOT NULL,
    PRODUCT_COUNT INT NOT NULL,
    CONSTRAINT FK_product_category_id FOREIGN KEY (CATEGORY_ID) REFERENCES CATEGORY
);

INSERT INTO CATEGORY(CATEGORY_ID, CATEGORY_NAME)
VALUES(1, 'Foreign books');

INSERT INTO PRODUCT(PRODUCT_ID, CATEGORY_ID, PRODUCT_NAME, PRODUCT_PRICE, PRODUCT_COUNT)
VALUES(1, 1, 'The Little Prince', 10.00, 100);

SELECT * FROM CATEGORY;
SELECT * FROM PRODUCT;

